language: cpp
    
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh github_package testthat
    
script:
  - R CMD INSTALL .
  - cd ..
  - git clone https://github.com/Rcpp11/Rcpp-test.git
  - R CMD INSTALL --install-tests Rcpp-test
  - cd Rcpp11
  - Rscript -e "require(RcppTest); require(testthat); require(devtools); test_package('RcppTest')"
  
after_script:
  - ./travis-tool.sh dump_logs
  
notifications:
  email:
    on_success: change
    on_failure: change

